import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.resolve(root, '../../../凯冰排版定稿');
const published = path.join(root, 'docs/kevinbee-final');
fs.mkdirSync(out, {recursive:true});
fs.mkdirSync(published, {recursive:true});
const save=(name,contents)=>{
 fs.writeFileSync(path.join(out,name),contents);
 fs.writeFileSync(path.join(published,name),contents);
};
const C={paper:'#FFFCF5',ink:'#22324A',blue:'#2768B2',ghost:'#C5D8EA',yellow:'#F3D55B',pale:'#FFF3CD',red:'#C94E4C',muted:'#647083',line:'#DFE4E6'};
const serif="Georgia,'Songti SC','STSong',serif";
const sans="-apple-system,BlinkMacSystemFont,'PingFang SC','Microsoft YaHei',sans-serif";
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const leaf=s=>`<span leaf="">${esc(s)}</span>`;
const span=(s,css)=>`<span style="${css}">${leaf(s)}</span>`;
const section=(s,css)=>`<section style="${css}">${s}</section>`;
const p=(s,css='')=>`<p style="margin:0 0 20px;font-size:17px;line-height:1.95;color:${C.ink};${css}">${s}</p>`;
function inline(s,keepConcepts=false){
 const rx=/(\*\*([^*]+)\*\*|==([^=]+)==|<u>(.*?)<\/u>|~~(.*?)~~|`([^`]+)`)/g;
 let result='',last=0,m;
 while((m=rx.exec(s))){result+=leaf(s.slice(last,m.index));const txt=m[2]??m[3]??m[4]??m[5]??m[6];
 const css=m[2]?`font-weight:700;color:${C.blue};`:m[3]?`font-weight:700;background:linear-gradient(transparent 58%,${C.yellow} 58%);padding:0 1px;`:m[4]?`text-decoration:underline;text-decoration-color:${C.blue};text-underline-offset:4px;`:m[5]?'text-decoration:line-through;':`font-family:Consolas,monospace;font-size:14px;background:#EDF2F6;padding:2px 4px;border-radius:3px;`;
 result+=span(txt,css+(keepConcepts&&m[3]&&txt.length<=6?'white-space:nowrap;':''));last=rx.lastIndex;}
 return result+leaf(s.slice(last));
}
const mark=()=>section(`<span style="display:inline-block;width:34px;height:4px;background:${C.blue};border-radius:2px;">${leaf('')}</span><span style="display:inline-block;width:17px;height:4px;background:${C.yellow};margin-left:6px;border-radius:2px;">${leaf('')}</span><span style="display:inline-block;width:5px;height:4px;background:${C.red};margin-left:6px;border-radius:2px;">${leaf('')}</span>`,'text-align:center;font-size:0;line-height:4px;margin:24px 0;');
const container=s=>section(s,`max-width:677px;box-sizing:border-box;margin:0 auto;padding:46px 22px 40px;background:${C.paper};font-family:${sans};color:${C.ink};overflow-wrap:break-word;`);
const title=t=>{
 const comma=t.indexOf('，');
 const layered=t.length>22&&comma>0;
 const lead=layered?p(inline(t.slice(0,comma+1)),`margin:0 0 10px;font-family:${serif};font-size:20px;font-weight:700;line-height:1.7;text-align:center;`):'';
 return section(lead+p(inline(layered?t.slice(comma+1):t),`margin:0;font-family:${serif};font-size:32px;font-weight:900;line-height:1.55;letter-spacing:.3px;text-align:center;`)+mark(),'padding:10px 0 14px;margin:0 0 22px;');
};
const chapter=(t,word,num)=>section(p(leaf(word),`margin:0 0 8px;font-family:${serif};font-size:64px;font-style:italic;font-weight:700;line-height:1.05;letter-spacing:-1px;color:${C.ghost};`)+p(leaf(t),`margin:0;font-family:${serif};font-size:26px;font-weight:900;line-height:1.55;`)+section(`<span style="display:inline-block;width:48px;height:5px;border-radius:3px;background:${C.yellow};vertical-align:middle;">${leaf('')}</span>${span(num,'font-family:Georgia,serif;font-size:12px;color:#6B7890;margin-left:12px;vertical-align:middle;')}`,'margin:14px 0 0;line-height:12px;'),'margin:52px 0 24px;');
const sub=t=>p(inline(t),`font-size:19px;font-weight:700;line-height:1.6;margin:30px 0 16px;padding-left:12px;border-left:4px solid ${C.blue};`);
const quote=(t,deep=false)=>section(p(inline(t,true),`margin:0;font-family:${serif};font-size:${deep?20:21}px;font-weight:700;line-height:1.9;color:${deep?'#FFFFFF':C.ink};`),`margin:24px 0 28px;padding:25px 22px;border-radius:14px;background:${deep?C.blue:C.pale};${deep?'':'text-align:center;'}`);
const list=(items,numbered=false)=>section(items.map((v,i)=>section(`<span style="display:inline-block;vertical-align:top;width:24px;padding-top:2px;font-size:13px;line-height:30px;font-weight:700;color:${C.blue};">${leaf(numbered?String(i+1).padStart(2,'0'):'•')}</span>${section(p(inline(v),'margin:0;'),'display:inline-block;vertical-align:top;width:calc(100% - 26px);')}`,'margin:0 0 13px;')).join(''),'margin:0 0 26px;');
const card=(t,body,bg=C.pale)=>section(p(inline(t),`font-size:16px;font-weight:700;margin:0 0 10px;`)+p(inline(body),'font-size:15px;margin:0;'),`margin:24px 0;padding:22px;border-radius:12px;background:${bg};`);
const code=(lines,dark=false)=>section(lines.map(l=>p(leaf(l),`margin:0;font-family:Consolas,monospace;font-size:13px;line-height:1.7;color:${dark?'#F3F6FB':C.ink};white-space:normal;`)).join(''),`margin:24px 0;padding:18px;border-radius:10px;background:${dark?C.ink:'#EDF3F8'};overflow-wrap:anywhere;`);
const divider=()=>section('<span leaf=""><br></span>',`height:1px;font-size:0;line-height:0;background:${C.line};margin:34px 0;`);
const source=fs.readFileSync(path.join(root,'assets/sample-article.md'),'utf8');
const semantics=['Value','Craft','System','Refine','Grow'];
let n=0,body='';
for(const b of source.trim().split(/\n\s*\n/)){
 if(b.startsWith('# '))body+=title(b.slice(2));
 else if(b.startsWith('## '))body+=chapter(b.slice(3),semantics[n],String(++n).padStart(2,'0'));
 else if(b.startsWith('### '))body+=sub(b.slice(4));
 else if(b.startsWith('> '))body+=quote(b.replace(/^> ?/gm,''),n>0);
 else if(b.startsWith('- '))body+=list(b.split('\n').map(x=>x.slice(2)));
 else if(b==='---')body+=mark()+divider();
 else if(b.startsWith('我是'))body+=p(inline(b),'font-size:14px;color:#647083;line-height:1.95;margin:0;');
 else body+=p(inline(b));
}
const article=container(body);
save('凯冰_文章正文.html',article);
// Compare all source words in order. Only structural chapter labels are extra.
const decode=s=>s.replace(/<[^>]*>/g,'').replaceAll('&quot;','"').replaceAll('&gt;','>').replaceAll('&lt;','<').replaceAll('&amp;','&');
let plain=decode(article);
for(const [i,w]of semantics.entries())plain=plain.replace(w,'').replace(String(i+1).padStart(2,'0'),'');
const expected=source.replace(/^#{1,3} |^> |^- |^---$/gm,'').replace(/\*\*|==|~~|<\/?u>/g,'').replace(/\s/g,'');
if(plain.replace(/[•\s]/g,'')!==expected)throw Error('Sample text changed');
const blocks=[];
const add=(name,html)=>blocks.push({name,html});
add('居中刊首',title('文章标题占位'));
add('带副标题刊首',title('文章标题占位')+p(leaf('原文副标题占位'),'text-align:center;font-size:16px;color:#647083;'));
add('短题刊首',title('短标题占位'));
add('起点章节',chapter('起点章节标题占位','Start','01'));
add('问题章节',chapter('问题章节标题占位','Why','02'));
add('方法章节',chapter('方法章节标题占位','Method','03'));
add('变化章节',chapter('变化章节标题占位','Change','04'));
add('收束章节',chapter('收束章节标题占位','Now','05'));
add('步骤编号章',chapter('步骤标题占位','01',''));
add('左线小节',sub('小节标题占位'));
add('行内小标题',p(span('原文小标题占位',`font-weight:700;color:${C.blue};`)));
add('正文',p(leaf('正文段落占位。使用开放式排版，保持完整的阅读宽度与稳定的左边界。')));
add('长段落',p(leaf('正文段落占位。用于检查较长中文段落的行长、行距和段落呼吸。标题负责引导，正文负责持续阅读。页面的大部分面积应属于连续内容，留白出现在章节转折处，段落之间保持自然的联系。')));
add('蓝色重点',p(inline('正文中的**重要判断占位**，保持原句完整。')));
add('黄色荧光',p(inline('正文中的==重点短语占位==，使用黄色半高荧光。')));
add('正文下划线',p(inline('正文中的<u>下划线占位</u>，保留原文标记。')));
add('原文删除线',p(inline('正文中的~~删除线占位~~，保留删除含义。')));
add('行内代码',p(inline('正文中的 `code` 保持等宽。')));
add('开场引言',quote('引言占位。原文已有的观点在这里建立阅读的起点。'));
add('蓝色判断',quote('引用内容占位。关键判断在这里形成一次明确的阅读停顿。',true));
add('开放引语',section(p(leaf('原文引语占位。'),`font-family:${serif};font-size:23px;font-weight:700;text-align:center;margin:0;`)+mark(),'margin:36px 0;'));
add('黄色旁注',card('原文旁注标题占位','补充说明占位。'));
add('蓝色信息',card('原文信息标题占位','信息内容占位。','#EAF2F9'));
add('红色提醒',card('原文提醒标题占位','提醒内容占位。','#FBECE7'));
add('完成说明',card('原文状态标题占位','状态说明占位。','#EBF3EB'));
add('无序列表',list(['列表项目占位一','列表项目占位二','列表项目占位三']));
add('有序列表',list(['步骤内容占位一','步骤内容占位二','步骤内容占位三'],true));
add('检查清单',list(['☐ 待确认项目占位','☑ 已完成项目占位']));
add('步骤说明',sub('原文步骤标题占位')+p(leaf('操作说明占位，保持步骤与解释紧密相连。')));
add('流程总览',list(['第一阶段占位','第二阶段占位','第三阶段占位'],true));
add('时间节点',sub('原文时间节点占位')+p(leaf('对应事件内容占位。')));
add('前后对比',card('原文前项标题占位','原文前项内容占位。','#EDF2F6')+card('原文后项标题占位','原文后项内容占位。',C.pale));
add('指标说明',section(p(leaf('00%'),`font-family:${serif};font-size:42px;color:${C.blue};margin:0;`)+p(leaf('原文指标说明占位'),'font-size:14px;margin:0;'),'padding:22px 0;border-top:2px solid #2768B2;margin:24px 0;'));
add('数据表格',`<table style="width:100%;border-collapse:collapse;font-size:14px;color:${C.ink};"><tbody><tr><th style="padding:12px 8px;background:${C.pale};text-align:left;">${leaf('字段占位')}</th><th style="padding:12px 8px;background:${C.pale};text-align:left;">${leaf('说明占位')}</th></tr><tr><td style="padding:12px 8px;border-bottom:1px solid ${C.line};">${leaf('维度占位')}</td><td style="padding:12px 8px;border-bottom:1px solid ${C.line};">${leaf('结果占位')}</td></tr></tbody></table>`);
add('浅色代码',code(['// 代码内容占位','const value = input;']));
add('深色代码',code(['// 代码内容占位','return value;'],true));
add('提示词',code(['任务目标占位','约束条件占位','输出要求占位']));
add('长内容阅读窗',p(leaf('上下滑动查看 ↓'),'font-size:12px;text-align:right;')+section(Array.from({length:16},(_,i)=>p(leaf(`补充材料第 ${i+1} 行占位。`),'font-size:14px;')).join(''),'max-height:240px;overflow-y:auto;padding:18px;background:#EDF3F8;border-radius:10px;'));
// These placeholders belong only to the component catalogue; the article contains no images.
const media=label=>section(p(leaf(label),'text-align:center;font-size:14px;margin:0;color:#647083;'),'padding:50px 18px;border:1px dashed #C8D3DC;background:#F2F6F8;border-radius:12px;margin:24px 0;');
add('原文图片位置',media('原文图片位置占位'));
add('原文图片说明',media('原文图片位置占位')+p(leaf('原文图注占位'),'text-align:center;font-size:12px;color:#647083;'));
add('原文双图对照',media('原文前图位置占位')+media('原文后图位置占位'));
add('原文图组',p(leaf('左右滑动查看 →'),'font-size:12px;text-align:right;')+section([1,2,3].map(i=>section(leaf(`原文图片 ${i} 位置占位`),'display:inline-block;vertical-align:top;box-sizing:border-box;width:86%;margin-right:12px;padding:48px 18px;background:#EDF3F8;font-size:14px;text-align:center;white-space:normal;')).join(''),'overflow-x:auto;white-space:nowrap;font-size:0;'));
add('原文视频待补位置',media('原文视频位置占位'));
add('问答',sub('原文问题占位')+p(leaf('原文回答内容占位。')));
add('延伸阅读',sub('原文延伸阅读标题占位')+list(['原文关联内容占位一','原文关联内容占位二']));
add('作者介绍',divider()+p(leaf('原文作者信息占位'),'font-size:14px;color:#647083;'));
add('资源说明',card('原文资源标题占位','原文资源说明与联系方式占位。','#EAF2F9'));
add('文末互动',p(leaf('原文互动引导占位。'),'font-size:15px;text-align:center;')+mark());
add('收束段落',quote('原文结尾内容占位。最后的判断以完整的句子收束。'));
const catalogue=container(blocks.map((b,i)=>`<!-- Block: ${String(i+1).padStart(2,'0')} ${b.name} -->`+p(leaf(`${String(i+1).padStart(2,'0')} / ${b.name}`),'font-size:12px;color:#647083;margin:38px 0 18px;border-top:1px solid #DFE4E6;padding-top:16px;')+b.html).join('\n'));
const cataloguePage=`<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>凯冰 · 明亮编辑 · 组件全览</title></head><body style="margin:0;background:${C.paper};">${catalogue}</body></html>`;
save('凯冰_组件全览.html',cataloguePage);
fs.writeFileSync(path.join(root,'assets/theme-previews/theme-kevinbee-editorial.html'),`<!-- THEME-NAME: 凯冰·明亮编辑 -->\n<!-- THEME-ID: theme-kevinbee-editorial -->\n${cataloguePage}`);
const preview=`<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>凯冰 · 明亮编辑</title><style>
*{box-sizing:border-box}body{margin:0;background:#EEEDE8;font-family:${sans};color:${C.ink}}.top{padding:27px 30px 23px;background:#F8F7F2;border-bottom:1px solid #DCDDD7;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{font-family:${serif};font-size:25px;font-weight:700}.tag{font-size:12px;color:#647083;margin-top:8px;letter-spacing:2px}.actions{display:flex;gap:9px;flex-wrap:wrap}button{font:inherit;font-size:13px;cursor:pointer;border:1px solid #CBD3D9;border-radius:6px;padding:10px 15px;background:transparent;color:${C.ink}}button.primary{background:${C.blue};color:white;border-color:${C.blue}}button[aria-pressed=true]{border-color:${C.blue};color:${C.blue};background:#EAF2F9}.layout{max-width:1060px;margin:36px auto 60px;display:grid;grid-template-columns:220px 1fr;gap:60px;padding:0 28px}.notes{padding-top:20px;font-size:13px;color:#637083;line-height:1.9}.notes h2{font-size:12px;letter-spacing:2px;color:${C.red};margin:0 0 14px;font-weight:600}.notes p{margin:0 0 24px}.swatches{display:flex;gap:8px;margin:25px 0}.swatches i{width:25px;height:25px;border-radius:50%;display:block}.notes a{color:${C.blue};text-underline-offset:4px}.paper{width:390px;max-width:100%;margin:0 auto;background:${C.paper};box-shadow:0 12px 55px #22324A0D}.paper.wide{width:677px}.status{min-height:22px;font-size:12px;text-align:center;color:${C.blue};padding:10px 15px}.mobile-note{display:none}footer{text-align:center;font-size:12px;color:#647083;padding:0 20px 30px} @media(max-width:760px){.top{padding:18px;display:block}.brand{font-size:23px}.actions{margin-top:16px}.layout{display:block;padding:0;margin:20px 0}.notes{display:none}.paper{box-shadow:none;width:390px}.mobile-note{display:block;font-size:12px;color:#647083;padding:0 20px 16px;line-height:1.7}footer{padding-top:12px}}
</style></head><body><header class="top"><div><div class="brand">凯冰 · 明亮编辑</div><div class="tag">公众号排版 · 定稿</div></div><div class="actions"><button id="mobile" aria-pressed="true">手机阅读</button><button id="wide" aria-pressed="false">宽屏阅读</button><button class="primary" id="copy">复制到公众号</button></div></header><main class="layout"><aside class="notes"><h2>阅读这版设计</h2><p>大字标记章节的意义。<br>宋体标题与明亮色彩，<br>给长文清楚的起伏。</p><div class="swatches"><i style="background:${C.blue}"></i><i style="background:${C.yellow}"></i><i style="background:${C.red}"></i><i style="background:${C.ink}"></i></div><p>淡蓝语义字 · 深墨标题<br>黄色荧光 · 蓝色引文<br>完整行宽 · 稳定左边界</p><p>当前使用项目已有文章演示排版，原文与作者署名均保留。凯冰是主题名称。</p><p><a href="凯冰_组件全览.html" target="_blank">查看整套组件 ↗</a><br><a href="凯冰_文章正文.html" download>下载正文 HTML ↓</a></p></aside><div><div class="mobile-note">以下为项目已有文章的排版样张，保留原文及原作者署名。</div><div class="status" id="status" role="status" aria-live="polite"></div><article class="paper" id="paper">${article}</article></div></main><footer>只有文章正文会被复制 · 主题说明与按钮不会进入公众号</footer><script>
const paper=document.getElementById('paper'),status=document.getElementById('status');
for(const id of ['mobile','wide'])document.getElementById(id).onclick=()=>{paper.classList.toggle('wide',id==='wide');for(const b of ['mobile','wide'])document.getElementById(b).setAttribute('aria-pressed',String(b===id));};
document.getElementById('copy').onclick=async()=>{const html=paper.innerHTML,text=paper.innerText;try{if(navigator.clipboard&&window.ClipboardItem){await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([text],{type:'text/plain'})})]);}else{throw Error('fallback');}status.textContent='正文已复制，请到公众号编辑器粘贴。';}catch{const sel=window.getSelection(),range=document.createRange();range.selectNodeContents(paper);sel.removeAllRanges();sel.addRange(range);const handler=e=>{e.clipboardData.setData('text/html',html);e.clipboardData.setData('text/plain',text);e.preventDefault();};document.addEventListener('copy',handler);let ok=false;try{ok=document.execCommand('copy');}finally{document.removeEventListener('copy',handler);}if(ok){sel.removeAllRanges();status.textContent='正文已复制，请到公众号编辑器粘贴。';}else{status.textContent='正文已选中，请按 ⌘C / Ctrl+C 复制。';}}};
</script></body></html>`;
save('凯冰_排版预览.html',preview);
console.log(JSON.stringify({out,published,blocks:blocks.length,textIntegrity:'PASS',images:0}));
